### ISSUE TITLE
Enable Logging

### ISSUE THREAD

**Issue by waaghals** [MaddieM4/cjdns-deb#1]
It should be logging by default.
Some people are having trouble getting up and running. Helping them without logging is difficult.

There isn't the possibility to let it log using cjdrouted. 

Could the logging also happen to /var/log/cjdns/cjdroute.log ?
The troubleshooter uses that location.

**Comment by MaddieM4** [comment]
Sure, I'll make that modification now. I can't test it for a couple days though, be sure to let me know of any issues with the patch.

**Comment by MaddieM4** [comment]
Let me know if this doesn't work properly. Also, because I did it over the github interface, it needs mkpackage.sh to be run to update cjdns.deb, so if you could do that, that would be awesome. I'll totally accept a pull request that does that.
